### ISSUE TITLE
the comment column in the group table is named wrong in the documentation.

### ISSUE THREAD

**Issue by mwoolweaver** [pi-hole/docs#412] opened 2020-10-29 16:52 UTC
### Versions

Pi-hole version is v5.1.2 (Latest: v5.1.2)
AdminLTE version is v5.1.1 (Latest: v5.1.1)
FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Linux Mint

- Platform:  iMac

### Expected behavior

docs to match database.

### Actual behavior / bug

column is not named correctly in documentation 

what it is.

Label | Type | Uniqueness enforced | Content
----- | ---- | ------------------- | --------
`id` | integer | Yes | Unique ID for database operations
`enabled` | boolean | No | Flag whether domains in this group should be used<br>(`0` = disabled, `1` = enabled)
`name` | text | No | Mandatory group name
`comment` | text | No | Optional field for arbitrary user comments

what was expected

Label | Type | Uniqueness enforced | Content
----- | ---- | ------------------- | --------
`id` | integer | Yes | Unique ID for database operations
`enabled` | boolean | No | Flag whether domains in this group should be used<br>(`0` = disabled, `1` = enabled)
`name` | text | No | Mandatory group name
`description` | text | No | Optional field for arbitrary user comments

### Steps to reproduce

1. Go to https://docs.pi-hole.net/database/gravity/groups/
2. look at first table on page
3. load gravity.db in [DB Browser](https://sqlitebrowser.org) 
4. check last column name and see it doesn't match.

## Debug Token

- URL:  

### Screenshots

Table as shown in [DB Browser](https://sqlitebrowser.org)

![screenshotList](https://user-images.githubusercontent.com/5729320/97606596-f7281c80-19dd-11eb-8368-b448f4687934.png)

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment] 2020-10-29 18:03
Duplicate of #411

**Comment by dschaper** [comment] 2020-10-29 18:04
Sorry, thought this was a PR.

Fixed by #411

**Closed** 2020-10-29 18:06 UTC
